### ISSUE TITLE
Drop in bazel build

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#102]
- [x] go gazelle rules
- [ ] go build rules
- [ ] code generation rules
- [ ] go container rules
- [ ] Kubernetes rules

**Comment by chrislovecnm** [comment]
@chrisseto just for you

**Comment by vladdy** [comment]
Is there a summary of what this change improves/makes possible? I'm not sure if Bazel provides any value for the projects, but increases the complexity.

**Comment by chrislovecnm** [comment]
@vladdy bazel is probably going to be used for multiple projects at CR.  Here are the advantages:

1. hermetic builds
2. deterministic builds
3. building docker without docker
4. better maintenance of container images
5. ability to handle k8s manifests with the build
6. better handling of release process, pushing containers, etc

Here is the big one: caching across CI builds for large projects.

Yes, it is complex, but with the added complexity come very large advantages. Just take a look at https://docs.bazel.build/versions/master/remote-execution.html.

**Comment by chrisseto** [comment]
We looking at using bazel in CC as well, largely for the caching advantages.

I had asked Chris to use bazel for this project so there would be a good example available to us!

**Comment by vladdy** [comment]
If you meant Cockroach Labs by CR, I understand why the database needs to switch to Bazel, it is a huge project which users multiple languages. For the advantages you listed:

1. hermetic builds - handled by Go since the operator does not need any cgo dependencies
2. deterministic builds - handled by Go 
3. building docker without docker  - can be done by other tooling such as Kanigko
4. better maintenance of container images -  not sure how "better" is measure here, but I think the only thing that is expected is an ability to upload the image.
5. ability to handle k8s manifests with the build - what do you mean by handling here? Usually manifests are generated and released as they are, so I'm not sure why entire Bazel is required to do so
6. better handling of release process, pushing containers, etc - again "better" is unclear here. 

> Here is the big one: caching across CI builds for large projects.

This is usually handled by CI and not by the build tools. TeamCity has a support for this and although I really hope the operator will become a large project, I'm not sure if it will reach the size where maintenance of complex build tool would justify the caching which is already provided by Go compiler. At the current stage I won't be surprised if this change would make the build slower.

> Yes, it is complex, but with the added complexity come very large advantages. 

This is true and it means that the advantages brought into the project needs to be justified. Right now, the justification is not that clear.

**Comment by vladdy** [comment]
> We're (read I) looking at using bazel in CC as well, largely for the caching advantages.

Sure, if CC needs something more complex than what Go can provide, however, I'm not sure if you can see real advantages of Bazel in this project. I.e. the current draft of PR adding Bazel support is close in number of lines to all the code we have under `pkg`

**Comment by chrislovecnm** [comment]
@vladdy all great points that I can counter, but alas there is code to write.  Yes, this project is spiking the introduction of Bazel into bigger projects.

@vladdy 90% of the code that is being checked in is autogenerated by bazel ;).   I am going to close this issue and break up what needs to be done initially.
