### ISSUE TITLE
Validate operator works properly on kubernetes 1.28, 1.29, 1.30

### ISSUE THREAD

**Issue by udnay** [cockroachdb/cockroach-operator#1039]
Validate that the operator works on the currently supported releases of kubernetes specifically 1.28,1.29 and 1.30. If we need to update the minimum version supported we should also do that.

@prafull01 can you take a look?

**Comment by prafull01** [comment]
Cockroach Operator working fine on k8s 1.30. We can safely assume there is no breaking change in 1.28 and 1.29. Otherwise it would not have been working on k8s 1.30
<img width="1440" alt="Screenshot 2024-07-19 at 7 23 55 PM" src="https://github.com/user-attachments/assets/756896b0-c058-46d3-aa8f-6bda67460482">
