### ISSUE TITLE
Are there plans to support other cloud platforms?

### ISSUE THREAD

**Issue by 70data** [cockroachdb/cockroach-operator#254]
CockroachDB Kubernetes Operator are there plans to support other cloud platforms, for example, the AWS、Alibaba Cloud and so on, not only GKE.
Or have any roadmap?

**Comment by chrislovecnm** [comment]
This operator is only tested on GKE is made to support other clouds as well.  The GKE cluster needs to have the certificate manager installed, or you need to create your own TLS certificates to use a secure cluster.

**Comment by 70data** [comment]
Are there any development plans?
This way we also test in other cloud scenarios and feed back to the community.

**Comment by chrislovecnm** [comment]
Test plans? What are you looking for?

**Comment by 70data** [comment]
Have any plans for further development of operators?
Whether to use the features of the cloud, or try to decouple from the cloud, or run in a private cloud scenario?

**Comment by chrislovecnm** [comment]
> Have any plans for further development of operators?

I will work with @johnrk to get a roadmap issue in GitHub.

> Whether to use the features of the cloud, or try to decouple from the cloud, or run in a private cloud scenario?

Two things are integration points.

1. PV/PVCs - we support using PV/PVCs out of the box as supported via K8s. We will remove support for EmptyDir soon, as it does not work with upgrades.  Otherwise, PV/PVCs are supported as usual.
2. We use the Kubernetes [certificate provider ](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/)to generate TLS certificates.  Some distributions do not support the certificate manager, so you need to provide your own certificates then.  You can set the certificate secret names and provider your own TLS certificates.

Where else do we need to integrate with a cloud?  I do not think we need any other cloud-specific integration.

> Alibaba Cloud、UCloud and private cloud

I would love feedback on running on all of those platforms!  

We plan on also testing on VMware and EKS.  We already tested on GKE and are working on making Openshift better.

Also, we would love to have help with the project as well.  Documentation, testing, fixing bugs, etc.!

**Comment by 70data** [comment]
Thanks a lot.
