### ISSUE TITLE
Version checking too rigid

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#331]
The version checking now only allows the versions that are listed in the operator manifest:

https://github.com/cockroachdb/cockroach-operator/blob/2912cae6a28c1fbe2e8bb46c025c80011143531b/manifests/operator.yaml#L276-L285

The following code needs to only run if the API field is being used instead of the image.

https://github.com/cockroachdb/cockroach-operator/blob/2912cae6a28c1fbe2e8bb46c025c80011143531b/pkg/actor/validate_version.go#L169'

If the image is defined then the user can run any version of crdb.

@keith-mcclellan should we be checking for a certain range of versions?

**Comment by chrislovecnm** [comment]
We need to log in LookupSupportVersion as well so the user can get feedback that an incorrect version was selected.

**Comment by keith-mcclellan** [comment]
We should be checking that the customer isn't trying to downgrade or upgrade too far regardless of whether they're using the CockroachVersion API or setting an image flag.  However, there are cases where this job won't return a "valid" version (if I have to use a custom build to fix a bug for example) so we need to have a way to force an upgrade to run.  Forced upgrades should always assume it's a feature release upgrade just in case since we won't be able to validate the upgrade path.

**Comment by chrislovecnm** [comment]
@keith-mcclellan we already have that logic in the partition update code.  We are not checking the negative test case in e2e, so we should probably do that.  But really that is for another issue.

**Comment by keith-mcclellan** [comment]
I created https://github.com/cockroachdb/cockroach-operator/issues/343 to track adding e2e testing enhancements so we can close this out if we want.

**Comment by chrislovecnm** [comment]
Closing this
