### ISSUE TITLE
Post Stop Binary

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#44]
@chrisseto can you sometimes walk me through https://github.com/cockroachdb/cockroach-operator/commit/3ef3a9330f24e2bf9ecb27eb1f576db2c463bd20 and if we still need it?

**Comment by chrisseto** [comment]
I added the post stop binary to automatically [decommission](https://www.cockroachlabs.com/docs/stable/remove-nodes.html) cockroach pods that were being removed from the cluster.

Cloud handles this by execing into pods that are going to be removed. We've found that the process can take anywhere between 5 minutes to 1 hour. Having the operator take care of decommissioning rather than the pod may be a better option?

**Comment by vladdy** [comment]
> Having the operator take care of decommissioning rather than the pod may be a better option? 

That's how I prototyped it.
