### ISSUE TITLE
Issue spinning up a new CrdbCluster with the same name as a deleted cluster - Operator on Openshift

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach-operator#505]
After getting a cluster into a weird state (see: https://github.com/cockroachdb/cockroach-operator/issues/504), I deleted my CrdbCluster instance from the OpenShift WebUI and tried to create a new CrdbCluster object.  I used the default name.

This new cluster bombed (i.e., never got past trying to spin up node 0) because the PV/PVCs still existed from the previous, weird cluster.

I wonder if we should either: 1) clean up PVs/PVCs when we delete CrdbCluster objects, or 2) check to see if we already have PVs/PVCs when we first create the CrdbCluster and deal with them then (delete them I guess).

**Comment by jhatcher9999** [comment]
I created a CrdbCluster with a new name and deleted the CrdbCluster and I noticed that we leave the PVs/PVCs in there (even though the cluster wasn't in a weird state).  I think we should delete these.

**Comment by keith-mcclellan** [comment]
#1 - we have a known issue with restarting with existing PVs, and it's resolved in a PR (https://github.com/cockroachdb/cockroach-operator/pullrequests/477) that should get merged this week.  Thanks for reporting.

#2 as for the cleanup, this is actually called out in the delete instructions.... we WANT you have to manually delete the PV/PVC/Secrets. We do this so that a customer can't accidentally delete both the cluster resources and their data in the same step.
