### ISSUE TITLE
Missing namespace on Role and RoleBinding options

### ISSUE THREAD

**Issue by jakedt** [cockroachdb/cockroach-operator#568]
In this file: https://github.com/cockroachdb/cockroach-operator/blob/v1.7.7/manifests/operator.yaml

The `Role` and `RoleBinding` objects need their namespaces defined or they will go in the default namespace defined by the kubecontext. I presume they need to be next to the cockroach operator itself.

**Comment by chrislovecnm** [comment]
@jakedt yes, those lines need to be included when you do not install the operator in the default namespace, but since the manifest is for the default namespace, you actually do not need the lines.

@taroface, do we have it documented how to install the operator in a different namespace?  @keith-mcclellan / @udnay I wonder if we should include the namespace line in the manifest, even though we do not need it, as you do not need it when you install it in the default namespace.  We could also document how to use kustomize to install the manifest in a custom namespace.

**Comment by jakedt** [comment]
The problem I ran into is that I *was* installing it in the default namespace, but my `kubeconfig` had it set so that anything that didn't have a namespace specified went into a `dev` namespace. Since your operator has a mix between resources that have a hardcoded namespace of default and some that don't, you end up with things in multiple namespaces.

**Comment by chrislovecnm** [comment]
@jakedt thanks for the follow-up!

**Comment by keith-mcclellan** [comment]
@chrislovecnm do you know what the LOE is on making the change you're suggesting? if its just updating the examples then that works for me.  Will we need to change anything else?

**Comment by taroface** [comment]
The [updated docs](https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-with-kubernetes.html#install-the-operator) mention how to install into a non-default namespace. I agree that the `Role` and `RoleBinding` namespace lines should be included in the `operator.yaml`.

**Comment by pseudomuto** [comment]
I believe this issue has been resolved. In the release referenced above, we can see that we used to have [a role](https://github.com/cockroachdb/cockroach-operator/blob/v1.7.7/manifests/operator.yaml#L51) with wildcard permissions.

This has changed since to used a more limited [ClusterRole](https://github.com/cockroachdb/cockroach-operator/blob/023d5df80505c763ac6a9bd794edc155931fc418/install/operator.yaml#L30) which allows the operator to run in a single namespace, or cluster scoped.
