### ISSUE TITLE
Labeling the default namespace in manifests

### ISSUE THREAD

**Issue by mbrancato** [cockroachdb/cockroach-operator#723]
While running into the issue #561 I noticed that the operator manifests label the `default` namespace.

A couple issues I see here. It's probably a bad practice to ever release a kubernetes add on that declaratively and authoritatively modifies the only namespace guaranteed to exist on all clusters. This would be fine for something like a `cockroach-system` namespace, but not `default`.

Additionally, anyone using a tool that does garbage collection to remove old resources (e.g. Flux) will likely have that tool try to delete the default namespace. I tried this out and did indeed see Flux attempt to delete the default namespace.
```
garbage collection failed: delete failed for Namespace/default: namespaces "default" is forbidden: this namespace may not be deleted
```

Additionally, there is a `cockroach-namespace` label being added to the namespace and presumably this is important. I was unable to identify the significance of this label by looking in the code nor in practice. The label doesn't seem necessary. Labels should have meanings, especially on namespaces (e.g. Istio's [auto side-car injection](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#automatic-sidecar-injection) label). If this isn't necessary, why include a `default` namespace resource in the manifest at all?

**Comment by pseudomuto** [comment]
> Additionally, there is a `cockroach-namespace` label being added to the namespace and presumably this is important. I was unable to identify the significance of this label by looking in the code nor in practice

Hey @mbrancato, thanks for raising this. The label is added to the namespace in order to allow the webhook configurations to use a namespaceSelector. This limits the webhooks to handling only resources the namespace specified by the `cockroach-namespace` label.

As for the use of the default namespace, I'm inclined to agree. At the moment we have a bunch of code, packaging scripts, and documentation that reference the default namespace, but ideally over time that would change. I think `cockroach-operator-system` would suffice for sure and be inline with what one might expect from other operators.

**Comment by mbrancato** [comment]
thanks @pseudomuto - Are you referring to what is described as the "watch namespace" in the code? It looks like you are. I still don't see where it looks up that key `cockroach-namespace` anywhere for use. I only see it settable via an environment variable on the operator deployment. Did I miss it somewhere?

**Comment by pseudomuto** [comment]
The watch namespace is different. That's used to set which namespaces the controller works with (currently only 1; the same one the operator is deployed in).

The cockroach-namespace label is used to [scope the webhooks](https://github.com/cockroachdb/cockroach-operator/blob/master/config/webhook/patches/webhook_config.yaml). Because the operator (at least currently) only controls resources in its own namespace, we need to be sure that the global admission controller hooks are scoped to avoid cases where we have v1alpha1 deployed in one namespace, and v1beta1 in another.

**Comment by mbrancato** [comment]
That makes sense @pseudomuto  - I think the confusion for me is around the label key. The label is being set as `cockroach-namespace` but the `matchLabels ` selector is pointing at `cockroach-operator`.

https://github.com/cockroachdb/cockroach-operator/blob/d567369897bd1a149a9f0f103d10395d63f5cc5d/manifests/operator.yaml#L18-L23

Either way, it seems like the webhooks are a rather new feature, not yet released.
