### ISSUE TITLE
Manifest YAML Does not have current CRDB versions indicated

### ISSUE THREAD

**Issue by carlsongould** [cockroachdb/cockroach-operator#823]
In our deploy cockroachdb with kubernetes openshift documentation we direct readers to reference the github manifest file.  In there it indicates the most recent version to be 20.2.8.  It does not indicate the latest versions of crdb. 

The manifest link is listed here (see bullet 3): https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-with-kubernetes-openshift.html#step-3-start-cockroachdb

**Comment by pseudomuto** [comment]
This is definitely the wrong link. I'll get that updated. In the meantime the correct link is https://github.com/cockroachdb/cockroach-operator/blob/b5ab268ca5453a00b27c3972f96c4a007737900d/install/operator.yaml#L375

This has changed since you've opened this issue. There was an issue where the versions weren't included in the env (see #848).
