### ISSUE TITLE
Communicate cluster upgrade status to crdb

### ISSUE THREAD

**Issue by Santamaura** [cockroachdb/cockroach-operator#856]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/cockroachdb/cockroach/issues/67330. In order for the UI to have a clear indication of when to show nodes upgrading during a rolling upgrade, we need an indication that an upgrade is occurring. 

**Describe the solution you'd like**
Some investigation will be needed first to confirm rolling upgrades are a first-class operation supported by our k8 operator. If it is the case we need to communicate this and expose it to the UI.

**Describe alternatives you've considered**
We have considered simply comparing node binary versions and if there are more than one versions we can consider a rolling upgrade to be in progress. This isn't adequate because  a user can add a node with a newer version to an older version cluster simply for testing purposes and delete it afterwards.

**Additional context**

**Comment by chrisseto** [comment]
Hey @Santamaura, thanks for the issue but this is out of scope of the operator. The operator is responsible for making changes to how the cluster is running but the state of the cluster should always flow upwards to the operator rather than the other way around. To phrase that in a different way: The cluster is the definitive source of truth for itself and the operator may only reflect and react to that truth.

I'm leaning towards [the solution proposed by Andrew](https://github.com/cockroachdb/cockroach/issues/67330#issuecomment-1043223575) as it will inform users of what's happening without trying to guess why it's happening. Based off my reading of the initial issue, it seems the desire is to track progress of a version change which is distinct from determining why or how a version change is occurring.

Feel free to re-open this issue if disagree!
